server:
  port: 20401
  mode: debug # debug, release, test

database:
  host: glimgate-mysql
  port: 3306
  username: root
  password: root123
  dbname: glimgate
  charset: utf8mb4
  parse_time: true
  loc: Local

jwt:
  secret: glimgate-jwt-secret-key-2024
  expire_hours: 24

cors:
  allow_origins:
    - "*"
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - "*"